### ISSUE TITLE
occurences of gate type

### ISSUE THREAD

**Issue by hklarner** [hklarner/RnaCancerClassifier#3]
`is_gate_type` sollte hier glaube ich ausserhalb des count constraints stehen, also anstatt von

```
% the number of occurences of a gate type is bounded
{gate_type(GateID,GateType): is_gate_type(GateType), is_gate_id(GateID)} X :- 
upper_bound_gate_occurence(GateType,X).
```

besser

```
{gate_type(GateID,GateType): is_gate_id(GateID)} X :- is_gate_type(GateType), 
upper_bound_gate_occurence(GateType,X).
```

andererseits sind die Lösungen in beiden Fällen wohl gleich..

**Comment by katinkab** [comment]
Da hast du Recht. Macht nur Sinn, wenn |GateType| // auch
|is_gate_type(GateType)| ist.

Weil wir für jeden /GateType /auch einen
|upper_bound_gate_occurence(GateType,X) |haben, ist das Ergebnis
wahrscheinlich gleich. Aber so ist es sinnvoller.
